name: Checkout and List
on: [push]
jobs:
  checkout-using-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List before checkout
        run: ls -a
      - name: checkout using actions
        uses: actions/checkout@v3
      - name: List after checkout
        run: ls -a
  checkout-and-display-filess:
    runs-on: ubuntu-latest
    steps:
      - name: List before checkout
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List after checkout
        run: ls -a