name: first-workflow
on: [push]

jobs:
  run-the-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Run Multiline Commands
        run: |
          node -v
          npm -v
  parallel-job:
    runs-on: macos-latest
    steps:
      - name: check sw version
        run: sw_vers
  dependent-job:
    runs-on: windows-latest
    needs: run-the-shell-commands
    steps:
      - name: print a string
        run: Write-Output "Windows is a Operating System"
      - name: error step
        run: thislinedoesntexist

  