name: Workflow Commands
on: [push]
jobs:
    testing-workflowcommands:
        runs-on: ubuntu-latest
        steps:
            - name: setting error message
              run: echo "::error::Missing Semicolon in the code"
            - name: setting error message with params
              run: echo "::error title=Error Title=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: setting debug message with params
              run: echo "::debug title=Debug Title=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: setting Warning message with params
              run: echo "::warning title=Warning Title=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: setting notice message with params
              run: echo "::notice title=Notice Title=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: group messages
              run: |
                echo "::group::My Group Title"
                echo "Inside Group"
                echo "::endgroup::"
            - name: masking a value
              run: echo "::add-mask:: Secret value"
            - name: Echo a secret
              run: echo "Secret value"